### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by brainomite** [crownheightsaid/airtable-change-detector#4]
When the `lastProcessedFieldName` is set to a value that is incorrect, Promises are being rejected.

**Comment by mjmaurer** [comment]
Yup I noticed that. I'm going to address a lot of these issues tonight. Expect a minor version release this week sometime

**Comment by mjmaurer** [comment]
Thanks for filing!

**Comment by mjmaurer** [comment]
1.1.0 is now released [with these changes](https://github.com/crownheightsaid/airtable-change-detector/blob/master/CHANGELOG.md)
